---
- name: Installation des serveurs web
  hosts: web
  remote_user: stf

  tasks:
    - name: Installation de Git
       apt: name-git update_cache=yes
    - name: Installation de VIM
       apt: name=vim
...
