---
- name: Installation des serveurs web
  hosts: web
  remote_user: root
  tasks: 
    - name: Installation de Git
      apt: name=git state=latest
    - name: Installation htop
      apt: name=htop state=latest		


- name: Show "salut les connards !"
  hosts: web
  remote_user: stf
  tasks:
    - name: Affichage "Salut les connards !"
      shell: echo 'Salut les connards !'
      register : stf	
  
...
