---
- name: Installation des serveurs web
  hosts: web
  remote_user: root
  tasks: 
    - name: Installation de Git
      apt: name=git state=latest
    - name: Installation htop
      apt: name=htop state=latest		



...
